micronutrientsupport/micronutrient-support-tool

- .github/workflows/develop-release.yml
Should deploy the head of `develop` to https://develop--micronutrientsupport-tool.netlify.app/ as a fixed URL for latest merged progress
> Add workflow to (hopefully) deploy to netlify on merge to develop

- src/app/pages/educationalResources/educationalResources.component.html
- src/app/pages/educationalResources/educationalResources.component.scss
- src/app/pages/help/help.component.html
- src/app/pages/help/help.component.scss
- src/app/pages/home/home.component.html
- src/app/pages/mapsTool/mapsTool.component.html
- src/app/pages/mapsTool/mapsTool.component.scss
- src/app/pages/projectObjectives/projectObjectives.component.html
- src/app/pages/projectObjectives/projectObjectives.component.scss
- src/assets/scss/_card.scss
- src/assets/scss/_page.scss
- src/assets/scss/_scroll.scss
- src/styles.scss
closes #139 
- attempt to reduce top areas of pages enough to show at least a taste of the content below
- switch the main scroll from body to html to interact better when dialogs are shown
> 139 map tools layout

- src/app/pages/quickMaps/components/sideNavContent/sideNavContent.component.ts
- src/app/pages/quickMaps/quickMaps.component.ts
- src/app/pages/quickMaps/quickMaps.service.ts
- navigate to quickmaps, select params, click "view results".
- The baseline page is displayed.
- Navigate to the maps tool page.
- Navigate back to the quickmaps page
> fix: ensure values set in query params if we have navigated back to quickmaps

- src/app/pages/quickMaps/quickMapsQueryParams.ts
- src/app/pages/quickMaps/quickMapsRouteGuard.service.ts
Routeguard will now allow access to this url, say:
https://preview347--micronutrientsupport-tool.netlify.app/quick-maps/diet/baseline?country-id=AGO&mnd-id=A&measure=diet&dataset-id=0&data-level=country
> fix: routeguard when accessing query params

- src/app/apiAndObjects/api/currentData/getDietarySources.ts
- src/app/apiAndObjects/api/currentData/getHouseholdHistogramData.ts
- src/app/apiAndObjects/api/currentData/getMonthlyFoodGroups.ts
- src/app/apiAndObjects/api/currentData/getProjectedAvailabilities.ts
- src/app/apiAndObjects/api/currentData/getSubRegionData.ts
- src/app/pages/quickMaps/components/sideNavContent/sideNavContent.component.html
- src/app/pages/quickMaps/components/sideNavContent/sideNavContent.component.ts
- src/app/pages/quickMaps/pages/baselineDetails/baselineDescription/baselineDescription.component.html
- src/app/pages/quickMaps/pages/baselineDetails/baselineDetails.component.ts
- src/app/pages/quickMaps/pages/baselineDetails/householdSupply/householdSupply.component.ts
- src/app/pages/quickMaps/pages/baselineDetails/mapView/mapView.component.ts
- src/app/pages/quickMaps/pages/baselineDetails/monthlyFood/monthlyFood.component.ts
- src/app/pages/quickMaps/pages/projection/projectionAvailability/projectionAvailability.component.ts
- src/app/pages/quickMaps/quickMaps.service.ts
- src/app/pages/quickMaps/quickMapsQueryParams.ts
- src/app/pages/quickMaps/quickMapsRouteGuard.service.ts
- src/app/services/currentData.service.ts
cache MicronutrientDataOption object in quickmaps service, rather than just the id, so that it is conveniently available for other api calls.
> Js further quickmaps params updates

- src/app/pages/quickMaps/pages/baselineDetails/baselineDescription/baselineDescription.component.html
- src/app/pages/quickMaps/pages/biomarkers/biomarkerDescription/biomarkerDescription.component.html
- src/app/pages/quickMaps/pages/projection/projectionDescription/projectionDescription.component.html
#482 
use term  "Micronutrient" rather than "Vitamin" and "Underlying Metric" rather than "Measure of MDN" on description cards
> use term  "Micronutrient"" and "Underlying Metric"

- src/app/pages/quickMaps/pages/dietaryChange/components/comparisonCard/comparisonCard.component.html
- src/app/pages/quickMaps/pages/dietaryChange/components/comparisonCard/comparisonCard.component.ts
- src/app/pages/quickMaps/pages/dietaryChange/components/options/options.component.ts
- src/app/pages/quickMaps/pages/dietaryChange/dietaryChange.item.ts
- src/app/pages/quickMaps/pages/dietaryChange/dietaryChange.module.ts
- src/app/pages/quickMaps/pages/dietaryChange/dietaryChange.service.ts
- src/app/pages/quickMaps/pages/dietaryChange/dietaryChangeMode.enum.ts
- src/app/pages/quickMaps/quickMaps.service.ts
add in a dietary change service and connect up the card to changes in the options
Probably gone to far , not having any idea about the data, corresponding api calls, and when they will need to be made, but it shows how some option changes can result in a new API  call and some can just re-use the current data and apply the newly selected value to it.
> Further dietary change scaffold

- .github/workflows/dependabot-auto-rebase.yml
Currently dependabot doesnt auto rebase open PRs after updates to Develop branch. This action triggers rebase for all dependabot PRs to ensure they are up to date.
> feat: after new pr auto rebase all open dependabot prs

- src/app/pages/quickMaps/pages/dietaryChange/components/comparisonCard/scenariosMap/scenariosMap.component.ts
Update the map to remove previous country when changing locations in deitary scenarios.
closes #652 
To test:
- https://preview674--micronutrientsupport-tool.netlify.app/quick-maps/diet/dietary-change?country-id=GIN&mnd-id=Ca&measure=diet&age-gender-group-id=WRA&sm=0&si=1594.01-54
> fix: close #652

- src/app/components/card/card.component.html
- src/app/components/card/card.component.scss
- closes #682 by truncating/adding elipsis dots to card title text when text is longer than the card
> Card title text does not overlap dialog button 

- src/app/pages/quickMaps/pages/dietaryChange/components/comparisonCard/scenariosMap/scenariosMap.component.ts
> fix: dietary change scenarios no longer errors when retrieving map colour gradient

- src/app/pages/quickMaps/components/sideNavContent/sideNavContent.component.html
- src/app/pages/quickMaps/components/sideNavContent/sideNavContent.component.ts
- src/app/pages/quickMaps/pages/baselineDetails/mapView/mapView.component.ts
- src/app/pages/quickMaps/pages/locationSelect/locationSelect.component.ts
- src/app/pages/quickMaps/pages/noResults/noResults.component.html
- src/app/pages/quickMaps/pages/noResults/noResults.component.scss
- src/app/pages/quickMaps/pages/noResults/noResults.component.ts
- src/app/pages/quickMaps/quickMaps-routing.module.ts
- src/app/pages/quickMaps/quickMaps.module.ts
- src/app/routes/routes.ts
Adds some basic validation of options which contain data and when none available, redirect users to an informative page. This should be re-visited in light of UX as there are many ways to either pre-validate (only show param options which are valid, therefore user can't make a 'mistake') or light-touch UI/UX features like toast indicators to keep user informed about what is happening and why something may not be working/results seem different to expectation.
- if selecting a new location, if there is no data available grey out/disable the view results button
- when viewing a country data, if user changes the side bar parameters, if there is no data available show a Not Found page with some basic information on what to do Currently placeholder text.
closes #689
> Allow missing data options in quickmaps to fail gracefully 

- src/app/components/card/card.component.html
- src/app/components/card/card.component.scss
- src/app/components/notifications/notification.component.html
- src/app/components/notifications/notification.component.scss
- src/app/components/notifications/notification.service.ts
- src/app/components/notifications/notificationData.ts
- card with erroring content now show a clearer message to say it is unavailable
- notification typography tweaked to emphasis error type/heading instead of the message.
- visit any section where there is not full data availability e.g.:
- https://preview713--micronutrientsupport-tool.netlify.app/quick-maps/diet/dietary-change?country-id=MWI&mnd-id=Ca&measure=diet&age-gender-group-id=WRA&sm=0&si=1312.01-9
- improve the UI of the empty content with imagery or suggestions on how to 'fix'. Needs some new asset imagery for missing content
> Card error UI improvement and notification tweak

- src/app/pages/quickMaps/pages/baselineDetails/foodItems/foodItems.component.html
- src/app/pages/quickMaps/pages/baselineDetails/foodItems/foodItems.component.ts
For country level units should be `/capita/day` e.g. https://preview726--micronutrientsupport-tool.netlify.app/quick-maps/diet/baseline?country-id=ETH&mnd-id=Ca&measure=diet&age-gender-group-id=WRA
For household level (MWI) should be `/AFE/day` e.g. https://preview726--micronutrientsupport-tool.netlify.app/quick-maps/diet/baseline?country-id=MWI&mnd-id=Ca&measure=diet&age-gender-group-id=WRA
Updated in both treemap and data table
> chore: correctly set treemap units depending on data level

- src/app/pages/quickMaps/pages/costEffectiveness/components/intervention/intervention.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview-routing.module.ts
- src/app/pages/quickMaps/pages/costEffectiveness/pages/interventionCompliance/interventionCompliance.component.html
- src/app/pages/quickMaps/quickMaps-routing.module.ts
- src/app/pages/quickMaps/quickMaps.module.ts
- src/app/pages/quickMaps/quickMapsRouteGuard.service.ts
- src/app/routes/routes.ts
*   Import `InterventionReviewModule` into the QuickMAPS module :star: 
*   Update parents of intervention pages to be the cost-effectivness module rather than intervention\_review
*   Replace some buttons with anchor links to aid in browser preview/debugging of urls
*   Fix review link in compliance page
All intervention pages (except intervention-baseline) work:
e.g. http://localhost:8100/quick-maps/diet/cost-effectiveness/intervention-compliance
http://localhost:8100/quick-maps/diet/cost-effectiveness/intervention-startup-scaleup-costs
Need to sort baseline still :shrug:
> fix: get intervention sub routing almost working

- src/app/components/dialogs/costEffectivenessSelectionDialog/costEffectivenessSelectionDialog.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/components/interventionCreation/interventionCreation.component.ts
- intervention was still added to list of selected intervention when pressing the 'cancel' button. Fix does not add empty object.
- Checks object exists instead of if name value exists on object
> fix: do not create intervention item on model cancel

- .vscode/settings.json
- src/app/apiAndObjects/api/api.service.ts
- src/app/apiAndObjects/api/intervention/interventionData/patchInterventionData.ts
- src/app/apiAndObjects/api/mapsHttpResponseHandler.ts
- src/app/components/footer/footer.component.html
- src/app/guards/featureFlagGuard.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionCostSummary/interventionCostSummary.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionCostSummary/interventionCostSummary.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionIndustryInformation/interventionIndustryInformation.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionIndustryInformation/interventionIndustryInformation.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionMonitoringInformation/interventionMonitoringInformation.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionMonitoringInformation/interventionMonitoringInformation.component.ts
- src/app/services/featureFlags.service.ts
- src/app/services/interventionData.service.ts
Addition to #883 
- each intervention GET is using the live API instead of cached data. This means that when moving between intervention pages it pulls the latest info each time, which includes any changes made in other pages.
- moved the store and send PATCH to intervention service which is called when confirming page, instead of when at cost summary page
- update industry intervention page to use string inputs instead of numbers, to enable 2 decimal place pipe to work
- ...which meant that needed to ensure that inputs were changes to numbers when building the PATCH request
> Extra work done on MR 883

- .vscode/settings.json
- src/app/apiAndObjects/api/api.service.ts
- src/app/apiAndObjects/api/intervention/interventionData/patchInterventionData.ts
- src/app/apiAndObjects/api/mapsHttpResponseHandler.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionCostSummary/interventionCostSummary.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionCostSummary/interventionCostSummary.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionIndustryInformation/interventionIndustryInformation.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionIndustryInformation/interventionIndustryInformation.component.ts
- src/app/services/interventionData.service.ts
Branching off from @kerberpolis work, I opted, instead of creating a subscription for each input, to make use of `this.form.valueChanges` to watch for updates. This should be much more performant than creating an individual subscription for every item we want to watch. 
One small issue we noticed was that the changes were only being detected on the 2nd change of an input value. As it turns out, this was due to the use of `pairwise()` operator from RXJS, which will only fire once it has an `oldValue` and a `newValue`. The fix was to make use of `startWith(this.form.value)` to tell it to use the default form value & pick up changes from the first click. 
After that it was a fairly simple task of comparing the 2 objects representing the old row values & the new row values and only retrieving …
> Watching for table changes to create PATCH call

- .vscode/settings.json
- src/app/components/dialogs/dialog.service.ts
- src/app/components/dialogs/sectionRecurringCostReviewDialog/sectionRecurringCostReviewDialog.component.html
- src/app/components/dialogs/sectionRecurringCostReviewDialog/sectionRecurringCostReviewDialog.component.scss
- src/app/components/dialogs/sectionRecurringCostReviewDialog/sectionRecurringCostReviewDialog.component.ts
- src/app/components/dialogs/sectionStartUpCostReviewDialog/sectionStartUpCostReviewDialog.component.html
- src/app/components/dialogs/sectionStartUpCostReviewDialog/sectionStartUpCostReviewDialog.component.scss
- src/app/components/dialogs/sectionStartUpCostReviewDialog/sectionStartUpCostReviewDialog.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionBaseline/interventionBaseline.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionCostSummary/components/detailedView/graphCosts/graphCosts.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionCostSummary/components/quickSummary/graphTotal/graphTotal.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionIndustryInformation/interventionIndustryInformation.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionMonitoringInformation/interventionMonitoringInformation.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionRecurringCosts/interventionRecurringCosts.component.scss
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionRecurringCosts/interventionRecurringCosts.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionReviewPages.scss
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionStartupScaleupCosts/interventionStartupScaleupCosts.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/utilities/interventionStepDetails/interventionStepDetails.component.scss
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/utilities/microNutrientsInPremixTable/premixTableRow/premixTableRow.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/utilities/reusableCostTable/reusableCostTable.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/utilities/reusableCostTable/reusableCostTable.component.ts
- src/app/services/interventionData.service.ts
- src/assets/scss/_angular_material_components.scss
- src/assets/scss/_colour.scss
- startup costs with dialogs patching data changes
- recurring costs with dialogs patching data changes
- updated industry information to track percentage data not just number
- added blue style to inputs which are modified
- look in the interventions pages at recurring costs and startup costs. Open the table dialogs, change values (which should show as blue when edited), confirm to close and save the changes, then reopen the dialog/refresh page and data should persist
- `.toFixed(2)` on input values are not being honoured. The appDecimal pipe ensures that user inputs are 2dp but if the original data is more than 2dp the `toFixed(2)` does not work.
> More use of PATCH endpoint for interventions

- src/app/apiAndObjects/_lib_code/api/apiCaller.ts
- src/app/apiAndObjects/api/biomarker/getBiomarkerDataSources.ts
- src/app/apiAndObjects/api/diet/getDietDataSources.ts
- src/app/apiAndObjects/api/diet/getMatchedTotals.ts
- src/app/apiAndObjects/api/diet/getMicronutrientAvailability.ts
- src/app/apiAndObjects/api/diet/getMonthlyFoodGroups.ts
- src/app/apiAndObjects/api/diet/getNationalSummary.ts
- src/app/apiAndObjects/api/diet/getTopFoods.ts
- src/app/apiAndObjects/api/projections/getMicronutrientProjectionSources.ts
- src/app/apiAndObjects/api/projections/getProjectionSummaries.ts
- src/app/apiAndObjects/api/projections/getProjectionTotals.ts
- src/app/apiAndObjects/api/scenario/getCurrentComposition.ts
- src/app/apiAndObjects/api/scenario/getCurrentConsumption.ts
- src/app/apiAndObjects/api/scenario/getDietChangeComposition.ts
- src/app/apiAndObjects/api/scenario/getDietChangeConsumption.ts
- src/app/apiAndObjects/api/scenario/getDietChangeFoodItem.ts
- src/app/apiAndObjects/objects/dictionaries/ageGenderDictionaryItem.ts
- src/app/apiAndObjects/objects/dictionaries/countryDictionaryItem.ts
- src/app/apiAndObjects/objects/dictionaries/foodGroupDictionaryItem.ts
- src/app/apiAndObjects/objects/dictionaries/impactScenarioDictionaryItem.ts
- src/app/apiAndObjects/objects/dictionaries/micronutrientDictionaryItem.ts
- src/app/components/dialogs/baseDialogService.abstract.ts
- src/app/pages/quickMaps/pages/biomarkers/biomarkerInfo/biomarkerInfo.component.ts
- src/app/pages/quickMaps/pages/biomarkers/biomarkerStatus/biomarkerStatus.component.ts
In the latest version of Angular(14) toPromise () has been deprecated. 
- removed .toPromise() from code and replaced with lastValueFrom()
https://indepth.dev/posts/1287/rxjs-heads-up-topromise-is-being-deprecated
https://stackoverflow.com/questions/69629634/are-lastvaluefrom-and-firstvaluefrom-equivalent-in-angular-http#:~:text=Since%20this%20a%20synchronous%20call,once%20complete()%20gets%20called.
> refactor: remove .toPromise() from code and replace with lastValueFrom()

- .github/workflows/deploy-staging.yml
- .npmrc
- Dockerfile
Removed .npmrc file to allow alternative registries to be picked up.
Github Actions defaults to npm registry correctly and builds and deploys.
Cypress borked, but unrelated to this (API issue)
> chore: tweak docker/npm config

- src/app/components/dialogs/sectionRecurringCostReviewDialog/sectionRecurringCostReviewDialog.component.html
- src/app/components/dialogs/sectionStartUpCostReviewDialog/sectionStartUpCostReviewDialog.component.html
- src/app/components/dialogs/sectionSummaryRecurringCostReviewDialog/sectionSummaryRecurringCostReviewDialog.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionAssumptionsReview/interventionAssumptionsReview.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionBaseline/interventionBaseline.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionBaseline/interventionBaseline.component.scss
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionCompliance/interventionCompliance.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionCompliance/interventionCompliance.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionCostSummary/components/detailedView/tableRecurringCosts/tableRecurringCosts.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionCostSummary/components/detailedView/tableStartupCosts/tableStartupCosts.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionCostSummary/components/quickSummary/tableTotalDiscounted/tableTotalDiscounted.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionCostSummary/components/quickSummary/tableTotalUndiscounted/tableTotalUndiscounted.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionIndustryInformation/interventionIndustryInformation.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionMonitoringInformation/interventionMonitoringInformation.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionReviewPages.scss
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/utilities/microNutrientsInPremixTable/premixTableRow/premixTable.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/utilities/reusableCostTable/reusableCostTable.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/utilities/reusableCostTable/reusableCostTable.component.scss
- src/assets/scss/_angular_material_components.scss
- src/assets/scss/_tables.scss
- src/assets/scss/_typography.scss
- src/environments/environment.base.ts
- tables use monospace font across the app again, this was disabled by css changes
- table columns centralised by default unless specified to left align
- dialogs using in-built title instead of custom one
- intervention review sidebar word wrapping instead of truncating
- do tables look ok?
- do table fonts look ok?
- do table headers align correctly?
- are there any elements missing the correct font and alignment to match similar?
> fix: table styling

- angular.json
- src/app/components/dialogs/costEffectivenessSelectionDialog/costEffectivenessSelectionDialog.component.scss
- src/app/pages/quickMaps/pages/baselineDetails/mapView/mapView.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/components/intervention/intervention.component.scss
- src/assets/scss/_tables.scss
- tables have padding to better fit within parent content
- table header cells removed padding to align with row content
- js defined in angular.json to mute warnings about bailouts
> fix: tweaks to tables, tidy js warnings

- src/app/components/dialogs/costEffectivenessSelectionDialog/costEffectivenessSelectionDialog.component.html
- src/app/components/dialogs/costEffectivenessSelectionDialog/costEffectivenessSelectionDialog.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/components/interventionCreation/interventionCreation.component.ts
- src/app/pages/quickMaps/quickMaps.component.html
- src/app/pages/quickMaps/quickMaps.component.scss
- src/app/services/dictionary.service.ts
- fork/load intervention dialog updated to show latest interventions from api instead of only on first load
- load interventions input now a dropdown list of latest interventions instead of manual number input
- only interventions above ID 3 are allowed to be loaded. This is hard coded for now but can use intervention parameter when api enables it
- load an intervention from the dialog using the drop down list
- fork an intervention, then open the dialog again and confirm that the newly created intervention can be loaded from the dropdown list
- only interventions iD > 3 can be loaded from the dropdown list
> feat: update add and load intervention dialog

- src/app/apiAndObjects/objects/dictionaries/interventionDictionaryItem.ts
- src/app/apiAndObjects/objects/intervention.ts
- src/app/components/dialogs/sectionRecurringCostReviewDialog/sectionRecurringCostReviewDialog.component.ts
- src/app/components/dialogs/sectionStartUpCostReviewDialog/sectionStartUpCostReviewDialog.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/components/intervention/intervention.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionCompliance/interventionCompliance.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionIndustryInformation/interventionIndustryInformation.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionMonitoringInformation/interventionMonitoringInformation.component.ts
-  show user edited fields in industry and monitoring stages
- intervention object updated to include extra API params like last edited and parent ID
- intervention card now shows last edited date
todo: baseline page, but currently its being poked so steering clear for now
> User edited inputs visible

- .vscode/settings.json
- src/app/components/dialogs/ceResetDialog/ceResetDialog.component.ts
- src/app/components/dialogs/sectionRecurringCostReviewDialog/sectionRecurringCostReviewDialog.component.html
- src/app/components/dialogs/sectionRecurringCostReviewDialog/sectionRecurringCostReviewDialog.component.ts
- src/app/components/dialogs/sectionStartUpCostReviewDialog/sectionStartUpCostReviewDialog.component.html
- src/app/components/dialogs/sectionStartUpCostReviewDialog/sectionStartUpCostReviewDialog.component.ts
- src/app/components/dialogs/sectionSummaryRecurringCostReviewDialog/sectionSummaryRecurringCostReviewDialog.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionBaseline/interventionBaseline.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionBaseline/interventionBaseline.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionCompliance/interventionCompliance.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionCompliance/interventionCompliance.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionIndustryInformation/interventionIndustryInformation.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionIndustryInformation/interventionIndustryInformation.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionMonitoringInformation/interventionMonitoringInformation.component.ts
-  wire up reset button to reset inputs to default values delivered via api
> Svea reset

- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview.module.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionAssumptionsReview/interventionAssumptionsReview.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionAssumptionsReview/interventionAssumptionsReview.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionBaseline/interventionBaseline.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionBaseline/interventionBaseline.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionCompliance/interventionCompliance.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionCompliance/interventionCompliance.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionCostSummary/interventionCostSummary.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionIndustryInformation/interventionIndustryInformation.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionIndustryInformation/interventionIndustryInformation.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionMonitoringInformation/interventionMonitoringInformation.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionMonitoringInformation/interventionMonitoringInformation.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionRecurringCosts/interventionRecurringCosts.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionRecurringCosts/interventionRecurringCosts.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionStartupScaleupCosts/interventionStartupScaleupCosts.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/utilities/reusableSkeletonTable/reusableSkeletonTable.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/utilities/reusableSkeletonTable/reusableSkeletonTable.component.scss
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/utilities/reusableSkeletonTable/reusableSkeletonTable.component.ts
- src/app/pipes/dataPropertyGetter.pipe.ts
- src/app/pipes/pipes.module.ts
- using skeleton loader package that can drop into any html template
- added dynamic table skeleton template with custom rows and columns
- added skeleton loaders into tables within intervention pages for slow connections
- view each page of the intervention steps and watch for a skeleton table to show before the data loads and a table of content replaces it
- this can be helped by turning dev tools > network > throttling to something like Fast 3G, as a wired network will get the data too quick to notice the change
> Skeleton loaders for drop-in to anywhere with a table
