- src/app/app-material.module.ts
- src/app/app.module.ts
- src/app/components/components.module.ts
- src/app/pages/home/home.component.html
- src/app/pages/home/home.component.scss
- src/app/pages/pages.module.ts
- src/assets/scss/_angular_materials.scss
- src/assets/scss/_register.scss
- src/assets/scss/_typography.scss
- src/assets/scss/_variables.scss
- src/styles.scss
- Restructured the angular materials to use custom theme with individual files for components e.g. typography
- added angular material import for use in pages and components
- using quicksand font as used in figma mockups
- using colour palette for primary and accent based on figma mockup
> Angular Material structure

- .vscode/settings.json
- src/app/app-routing.module.ts
- src/app/pages/pages.module.ts
- src/app/pages/quickMaps/pages/components/mapPage/mapPage.component.html
- src/app/pages/quickMaps/pages/components/mapPage/mapPage.component.scss
- src/app/pages/quickMaps/pages/components/mapPage/mapPage.component.ts
- src/app/pages/quickMaps/pages/components/sideNavContent/sideNavContent.component.html
- src/app/pages/quickMaps/pages/components/sideNavContent/sideNavContent.component.ts
- src/app/pages/quickMaps/pages/quickMaps.component.html
- src/app/pages/quickMaps/pages/quickMaps.component.scss
- src/app/pages/quickMaps/pages/quickMaps.component.ts
- src/app/pages/quickMaps/quickMaps.module.ts
- restructure of components and modules in quickmaps area
> Dw sr quickmaps retructure

- src/app/pages/home/home.component.html
- src/app/pages/home/home.component.scss
- src/app/pages/home/home.component.ts
- src/app/pages/mapsTool/mapsTool.component.html
- src/app/pages/mapsTool/mapsTool.component.scss
- src/app/pages/pages.module.ts
- src/assets/scss/_card.scss
- src/assets/scss/_utilities.scss
- src/styles.scss
- added new page for MAPS Tools and links from home page
- updated layout for some grid items
- disabled the custom breakpoints for now - need discussion
> Added Map tools content page

- .github/workflows/e2e.yml
- cypress/integration/home.ts
- cypress/integration/quick-maps.ts
- cypress/integration/spec.ts
- package-lock.json
- package.json
- src/app/components/dialog/share/dialogShare.component.html
- src/app/components/header/header.component.html
- src/app/pages/home/home.component.html
- src/app/services/sharing.service.ts
- updated cypress
- added some v.basic e2e tests for sharing and quick maps
- added e2e CI stage in github actions with cypress
> Added some more basic e2e testing

- src/app/apiAndObjects/api/api.service.ts
- src/app/apiAndObjects/api/mapsHttpResponseHandler.ts
- src/app/apiAndObjects/objects/dictionaries/countryRegionDictionaryItem.ts
- src/app/pages/quickMaps/components/sideNavContent/sideNavContent.component.html
- src/environments/environment.base.ts
The real list will appear in the quickmaps sidenav
> implement real api endpoint for countries

- cypress/integration/quick-maps.ts
- src/app/pages/quickMaps/components/quickMapsHeader.component/quickMapsHeader.component.html
- src/app/pages/quickMaps/components/quickMapsHeader.component/quickMapsHeader.component.scss
- src/app/pages/quickMaps/components/quickMapsHeader.component/quickMapsHeader.component.ts
- src/app/pages/quickMaps/components/sideNavContent/sideNavContent.component.html
- src/app/pages/quickMaps/components/sideNavContent/sideNavContent.component.scss
- src/app/pages/quickMaps/components/sideNavContent/sideNavContent.component.ts
- src/app/pages/quickMaps/pages/baselineDetails/baselineDetails.component.html
- src/app/pages/quickMaps/pages/baselineDetails/baselineDetails.component.scss
- src/app/pages/quickMaps/pages/baselineDetails/baselineDetails.component.ts
- src/app/pages/quickMaps/pages/baselineDetails/map-view/map-view.component.ts
- src/app/pages/quickMaps/pages/locationSelect/locationSelect.component.html
- src/app/pages/quickMaps/pages/locationSelect/locationSelect.component.ts
- src/app/pages/quickMaps/pages/projection/projection.component.html
- src/app/pages/quickMaps/pages/projection/projection.component.scss
- src/app/pages/quickMaps/quickMaps-routing.module.ts
- src/app/pages/quickMaps/quickMaps.component.html
- src/app/pages/quickMaps/quickMaps.component.scss
- src/app/pages/quickMaps/quickMaps.component.ts
- src/app/pages/quickMaps/quickMaps.module.ts
- src/app/pages/quickMaps/quickMaps.service.ts
- src/app/pages/quickMaps/quickMapsQueryParams.ts
- src/app/pages/quickMaps/quickMapsRouteGuard.service.ts
- src/app/routes/routes.ts
- src/app/services/currentData.service.ts
- src/assets/scss/_scroll.scss
- quickmaps sub-router implemented
- routerlinks updated to include query params
- sidenav styling tweaked
- e2e tests updated
> quickmaps navigation updates

- src/app/pages/quickMaps/pages/baselineDetails/food-composition-view/food-composition-view.component.html
- src/app/pages/quickMaps/pages/baselineDetails/food-composition-view/food-composition-view.component.ts
update title of "Food composition" card to "Data sources & Methods"
closes #149
> fix: update title of "Food composition" card to "Data sources & Methods"

- src/app/pages/quickMaps/pages/baselineDetails/baselineDetails.component.html
> fix: remove quick maps "summarised data table"

- src/app/pages/quickMaps/pages/baselineDetails/map-view/map-view.component.html
- src/app/pages/quickMaps/pages/baselineDetails/map-view/map-view.component.ts
- src/app/pages/quickMaps/quickMaps.service.ts
closes #148 
- update quickmaps map view card with country name - currently does from country dictionary but will probbaly be fed from the api data after #170 complete.
- Removed some not-needed code from the quickmaps service
> Js map card country

- cypress/integration/home.ts
- src/app/components/footer/footer.component.html
- src/app/components/header/header.component.html
> chore: update main app title and footer names. 

- src/app/pages/quickMaps/pages/baselineDetails/baselineDetails.component.scss
- src/app/pages/quickMaps/pages/baselineDetails/foodItems/foodItems.component.ts
- src/app/pages/quickMaps/pages/baselineDetails/householdCard/householdCard.component.ts
- src/app/pages/quickMaps/pages/baselineDetails/monthlyCard/monthlyCard.component.ts
-  quickmaps cards loading spinners fix
- quickmaps cards dynamic updates fix
- reduction in gridster resize grab handles
> fix: loading spinners and dynamic updates on quickmaps cards

- src/app/app.component.ts
- src/app/pages/quickMaps/quickMaps.component.ts
- no "view results" button was showing on quickmaps if first page loaded was "map tools", for instance
> fix: no go button was showing on quickmaps first nav

- src/app/pages/quickMaps/components/sideNavContent/sideNavContent.component.html
- src/app/pages/quickMaps/components/sideNavContent/sideNavContent.component.scss
- src/app/pages/quickMaps/components/sideNavContent/sideNavContent.component.ts
- Removed limit from select width
- Closes #147
> fix: overflow Text in select #147

- src/app/pages/quickMaps/pages/projection/projectionAvailability/projectionAvailability.component.html
- src/app/pages/quickMaps/pages/projection/projectionAvailability/projectionAvailability.component.scss
- src/app/pages/quickMaps/pages/projection/projectionAvailability/projectionAvailability.component.ts
- Containers using MAPS scroll style
- Chart and table now responsive to country selected in drop down.
> feat: chart and table now responsive to selected country

- .github/dependabot.yml
Limit number of open dependabot Pull requests
> chore: limit number of open dependabot pr

- src/app/pages/quickMaps/components/sideNavContent/sideNavContent.component.html
- src/app/pages/quickMaps/components/sideNavContent/sideNavContent.component.scss
fixed fire-fox issue and awaiting review: closes #295
> fixed the firefox bug and awaiting review

- src/app/apiAndObjects/objects/impactScenario.ts
- src/app/pages/quickMaps/components/quickMapsHeader.component/quickMapsHeader.component.ts
the impact scenario was not using correct keys, fixes issue with wrong impact scenario being used
> Stever fixaroony

- src/environments/environment.base.ts
- src/environments/environment.prod.ts
updates to point both dev and prod builds to the "devapi" externally available api
> point to the devapi

- src/app/apiAndObjects/api/currentData/getDietarySources.ts
- src/app/apiAndObjects/api/currentData/getHouseholdHistogramData.ts
- src/app/apiAndObjects/api/currentData/getMicroNutrientDataOptions.ts
- src/app/apiAndObjects/api/currentData/getMonthlyFoodGroups.ts
- src/app/apiAndObjects/api/currentData/getProjectedAvailabilities.ts
- src/app/apiAndObjects/api/currentData/getSubRegionData.ts
- src/app/apiAndObjects/api/currentData/getTopFood.ts
- src/app/pages/quickMaps/components/sideNavContent/sideNavContent.component.html
- src/app/pages/quickMaps/components/sideNavContent/sideNavContent.component.ts
- src/app/pages/quickMaps/pages/baselineDetails/baselineDescription/baselineDescription.component.html
- src/app/pages/quickMaps/pages/baselineDetails/baselineDescription/baselineDescription.component.ts
- src/app/pages/quickMaps/pages/baselineDetails/baselineDetails.component.ts
- src/app/pages/quickMaps/pages/baselineDetails/foodItems/foodItems.component.ts
- src/app/pages/quickMaps/pages/baselineDetails/householdSupply/householdSupply.component.ts
- src/app/pages/quickMaps/pages/baselineDetails/mapView/mapView.component.ts
- src/app/pages/quickMaps/pages/baselineDetails/monthlyFood/monthlyFood.component.ts
- src/app/pages/quickMaps/pages/locationSelect/locationSelect.component.ts
- src/app/pages/quickMaps/pages/projection/projectionAvailability/projectionAvailability.component.ts
- src/app/pages/quickMaps/pages/projection/projectionDescription/projectionDescription.component.ts
- src/app/pages/quickMaps/quickMaps.service.ts
- src/app/pages/quickMaps/quickMapsRouteGuard.service.ts
- src/app/services/currentData.service.ts
- Update the quickmaps service to store the country rather than just it's code.
- pass the country object in for api calls rather than just the id
> Js further quickmaps params updates 2

- src/app/pages/quickMaps/pages/baselineDetails/foodItems/foodItems.component.html
- src/app/pages/quickMaps/pages/baselineDetails/foodItems/foodItems.component.ts
Removing `<div class="bmgf-maps-nice-scrollbar">` from the card fixes the tree card not resizing. Removing from this card fixes immediate issue without impacting other cards which are working okay (AFAICT)
> fix: tree view working again

- src/app/apiAndObjects/api/currentData/getProjectedFoodSources.ts
- src/app/apiAndObjects/objects/projectedFoodSources.ts
- src/app/pages/quickMaps/pages/projection/projectionFoodSources/projectionFoodSources.component.ts
- src/app/services/currentData.service.ts
- projected food source card now has live data wired into the food group / commodity drop down
> Added food-group to projected food source

- src/app/pages/quickMaps/pages/baselineDetails/baselineDescription/baselineDescription.component.html
- src/app/pages/quickMaps/pages/projection/projectionDescription/projectionDescription.component.html
- src/app/pages/quickMaps/pages/projection/projectionDescription/projectionDescription.component.scss
- src/app/pages/quickMaps/pages/projection/projectionDescription/projectionDescription.component.ts
- add "Measure of MDN" to quickmaps diet description widgets
- Also ensure that the projection version is the same as the baseline one.
> feat: add "Measure of MDN" to quickmaps diet description widgets

- src/app/apiAndObjects/api/currentData/getTopFood.ts
enable top20 food live api call for "household" data level
> feat: enable top20 food live api call for "household" data level

- .github/workflows/build.yml
Fixes the CI action issues which have been failing all dependabot PRs
> chore: deploy github action update

- .vscode/settings.json
- src/app/pages/quickMaps/pages/biomarkers/biomarker.component.html
- src/app/pages/quickMaps/pages/biomarkers/biomarker.component.scss
- src/app/pages/quickMaps/pages/biomarkers/biomarker.component.ts
- src/app/pages/quickMaps/pages/biomarkers/biomarker.module.ts
- src/app/pages/quickMaps/pages/biomarkers/biomarkerDescription/biomarkerDescription.component.html
- src/app/pages/quickMaps/pages/biomarkers/biomarkerDescription/biomarkerDescription.component.scss
- src/app/pages/quickMaps/pages/biomarkers/biomarkerDescription/biomarkerDescription.component.ts
- src/app/pages/quickMaps/quickMaps.module.ts
Added Gridster - mirrored implementation done in Baseline Details
Added Summary Card 
Area now ready to add cards
> feat: added gridster and summary card

- src/app/apiAndObjects/api/api.service.ts
- src/app/apiAndObjects/api/currentData/getAgeGenderGroups.ts
- src/app/apiAndObjects/objects/ageGenderGroup.ts
- src/app/services/currentData.service.ts
- src/assets/exampleData/age-gender-groups.json
Adds api code associated with #416
> feat: add an API endpoint etc. for age-gender groups

- src/app/components/card/card.component.html
- src/app/components/card/card.component.ts
- src/app/pages/quickMaps/pages/baselineDetails/foodItems/foodItems.component.html
- src/app/pages/quickMaps/pages/baselineDetails/foodItems/foodItems.component.ts
- src/app/pages/quickMaps/pages/baselineDetails/householdSupply/householdSupply.component.html
- src/app/pages/quickMaps/pages/baselineDetails/householdSupply/householdSupply.component.ts
- src/app/pages/quickMaps/pages/baselineDetails/mapView/mapView.component.html
- src/app/pages/quickMaps/pages/baselineDetails/mapView/mapView.component.ts
- src/app/pages/quickMaps/pages/baselineDetails/monthlyFood/monthlyFood.component.html
- src/app/pages/quickMaps/pages/baselineDetails/monthlyFood/monthlyFood.component.ts
- src/app/pages/quickMaps/pages/biomarkers/biomarkerInfo/biomarkerInfo.component.html
- src/app/pages/quickMaps/pages/biomarkers/biomarkerInfo/biomarkerInfo.component.ts
- src/app/pages/quickMaps/pages/biomarkers/biomarkerStatus/biomarkerStatus.component.html
- src/app/pages/quickMaps/pages/biomarkers/biomarkerStatus/biomarkerStatus.component.ts
- src/app/pages/quickMaps/pages/projection/projectionAvailability/projectionAvailability.component.html
- src/app/pages/quickMaps/pages/projection/projectionAvailability/projectionAvailability.component.ts
- src/app/pages/quickMaps/pages/projection/projectionFoodSources/projectionFoodSources.component.html
- src/app/pages/quickMaps/pages/projection/projectionFoodSources/projectionFoodSources.component.ts
- src/assets/scss/_angular_material_components.scss
- src/assets/scss/_card.scss
- each info tab will contain information about the content of the card, content TBC
Related issue #485
> feat: added information tab to each chart and map

- src/app/apiAndObjects/objects/misc/chartjsObject.ts
- src/app/pages/quickMaps/pages/projection/projection.module.ts
- src/app/pages/quickMaps/pages/projection/projectionFoodSources/projectionFoodSources.component.html
- src/app/pages/quickMaps/pages/projection/projectionFoodSources/projectionFoodSources.component.scss
- src/app/pages/quickMaps/pages/projection/projectionFoodSources/projectionFoodSources.component.ts
- src/app/pages/quickMaps/quickMaps.module.ts
> Projection Food source card QOL improvements

- src/app/components/dialogs/mapSettingsDialog/mapSettingsDialog.component.html
- src/app/pages/quickMaps/quickMaps.component.html
- Minor change to sidenavs to prevent them from closing on escape keypress
- resolves issue #523
> fix: sidenavs no longer close on esc key press

- src/app/pages/quickMaps/pages/dietaryChange/components/comparisonCard/scenariosMap/scenariosMap.component.ts
- Using timeout to create a better user experience when tracking maps.
> refactor: updated mechanism which allows maps to track each other.

- src/app/pages/quickMaps/pages/dietaryChange/components/comparisonCard/scenariosMap/scenariosMap.component.html
- src/app/pages/quickMaps/pages/dietaryChange/components/comparisonCard/scenariosMap/scenariosMap.component.scss
- src/app/pages/quickMaps/pages/dietaryChange/components/comparisonCard/scenariosMap/scenariosMap.component.ts
- Added titles to maps
- Displaying message over map to notify user to set a scenario
- ensured message appears on load
Resolves #503
> Dw dietary map updates

- src/app/pages/quickMaps/components/sideNavContent/sideNavContent.component.html
- src/app/pages/quickMaps/pages/baselineDetails/baselineDescription/baselineDescription.component.html
- src/app/pages/quickMaps/pages/baselineDetails/foodItems/foodItems.component.html
- src/app/pages/quickMaps/pages/baselineDetails/householdSupply/householdSupply.component.html
- src/app/pages/quickMaps/pages/baselineDetails/householdSupply/householdSupply.component.ts
- src/app/pages/quickMaps/pages/baselineDetails/mapView/mapView.component.html
- src/app/pages/quickMaps/pages/baselineDetails/mapView/mapView.component.ts
- src/app/pages/quickMaps/pages/baselineDetails/monthlyFood/monthlyFood.component.html
- src/app/pages/quickMaps/pages/baselineDetails/monthlyFood/monthlyFood.component.ts
Title, about and more info text updates for multiple cards
closes #537 #538 #540 #539 #541 #542
> Title, about and more info text updates for multiple cards

- .github/workflows/build.yml
- .github/workflows/bundle.yml
- .github/workflows/develop-release.yml
- .github/workflows/e2e.yml
- .github/workflows/lighthouse.yml
updating all current github actions before attempting to debug failures in PR pipelines
> chore: update action versions

- src/app/apiAndObjects/api/api.service.ts
- src/app/apiAndObjects/api/diet/getUnmatchedTotals.ts
- src/app/apiAndObjects/objects/unmatchedTotals.ts
- src/app/components/dialogs/baselineDescriptionDialog/baselineDescriptionDialog.component.html
- src/app/components/dialogs/baselineDescriptionDialog/baselineDescriptionDialog.component.scss
- src/app/components/dialogs/baselineDescriptionDialog/baselineDescriptionDialog.component.ts
- src/app/pages/quickMaps/pages/baselineDetails/baselineDescription/baselineDescription.component.html
- src/app/pages/quickMaps/pages/baselineDetails/baselineDescription/baselineDescription.component.ts
- src/app/services/dietData.service.ts
*   API boilerplate code for new endpoint
*   Update endpoint data when baseline query params change
*   Display outputs in baseline summary card
*   Populate baseline summary "more info" modal
> Add unmatched totals endpoint

- src/app/decorators/unsubscriber.decorator.ts
- src/app/pages/quickMaps/pages/baselineDetails/baselineDescription/baselineDescription.component.ts
- src/app/pages/quickMaps/pages/baselineDetails/foodItems/foodItems.component.ts
- src/app/pages/quickMaps/pages/baselineDetails/monthlyFood/monthlyFood.component.ts
- small fix related to discussions in #647 to increase the legibility and usability of the charts
> Remove the legend below the monthly charts for increased legibility

- src/app/apiAndObjects/_lib_code/api/apiCaller.ts
- src/app/apiAndObjects/_lib_code/api/httpResponseHandler.interface.ts
- src/app/apiAndObjects/api/diet/getMicronutrientAvailability.ts
- src/app/apiAndObjects/api/mapsHttpResponseHandler.ts
- src/app/apiAndObjects/objects/mnAvailibilityCountryItem.ts
- src/app/pages/quickMaps/pages/baselineDetails/mapView/mapView.component.ts
- src/app/pages/quickMaps/pages/dietaryChange/components/comparisonCard/comparisonCard.component.html
- src/app/pages/quickMaps/pages/dietaryChange/components/comparisonCard/comparisonCard.component.ts
- src/app/pages/quickMaps/pages/dietaryChange/components/comparisonCard/scenariosMap/scenariosMap.component.ts
- src/app/services/dietData.service.ts
update api handler to support full response return rather than just data array. 
Add support for setting choropleth bins from API meta response
> feat: api choropleth updates

- .vscode/settings.json
- src/app/pages/quickMaps/components/quickMapsHeader.component/quickMapsHeader.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/components/costEffectivenessComponents.module.ts
- src/app/pages/quickMaps/pages/costEffectiveness/components/description/description.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/components/description/description.component.scss
- src/app/pages/quickMaps/pages/costEffectiveness/components/description/description.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/costEffectiveness.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/costEffectiveness.component.scss
- src/app/pages/quickMaps/pages/costEffectiveness/costEffectiveness.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/costEffectiveness.module.ts
- src/app/pages/quickMaps/pages/costEffectiveness/costEffectiveness.service.ts
- src/app/pages/quickMaps/quickMaps-routing.module.ts
- src/app/pages/quickMaps/quickMaps.module.ts
- src/app/routes/routes.ts
Scaffolded area for Cost Effectiveness Scenarios and added routing.
> Dw 667 costs scaffold

- src/app/apiAndObjects/objects/mnAvailibilityItem.abstract.ts
- src/app/pages/quickMaps/pages/baselineDetails/foodItems/foodItems.component.ts
- src/app/pages/quickMaps/pages/baselineDetails/mapView/mapView.component.ts
- card title shows more information about the contents 
- mouse hover on map data shows more useful information 
close #620 @bgsandan can confirm if this MR meets the issue requirements
close #692
> Baseline map updates

- src/app/pages/quickMaps/pages/costEffectiveness/components/costEffectivenessComponents.module.ts
- src/app/pages/quickMaps/pages/costEffectiveness/components/interventionComparison/interventionComparison.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/components/interventionComparison/interventionComparison.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/components/interventionCreation/interventionCreation.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/components/interventionCreation/interventionCreation.component.scss
- src/app/pages/quickMaps/pages/costEffectiveness/components/interventionCreation/interventionCreation.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/components/menu/menu.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/components/menu/menu.component.scss
- src/app/pages/quickMaps/pages/costEffectiveness/components/menu/menu.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/costEffectiveness.component.html
- Created 'menu' area for accessing intervention creation and intervention comparison.
- Fleshed out basic intervention creation layout.
> Dw further scaffolding

- src/app/pages/quickMaps/pages/costEffectiveness/components/costEffectivenessComponents.module.ts
- src/app/pages/quickMaps/pages/costEffectiveness/components/intervention/intervention.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/components/intervention/intervention.component.scss
- src/app/pages/quickMaps/pages/costEffectiveness/components/intervention/intervention.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/costEffectiveness.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/costEffectiveness.component.scss
- src/app/pages/quickMaps/pages/costEffectiveness/costEffectiveness.module.ts
> Sr ce intervention card

- src/app/apiAndObjects/api/api.service.ts
- src/app/apiAndObjects/api/dictionaryType.enum.ts
- src/app/apiAndObjects/objects/dictionaries/interventionDictionaryItem.ts
- src/app/components/dialogs/costEffectivenessSelectionDialog/costEffectivenessSelectionDialog.component.html
- src/app/components/dialogs/costEffectivenessSelectionDialog/costEffectivenessSelectionDialog.component.ts
- src/app/components/dialogs/dialog.service.ts
- src/app/pages/quickMaps/pages/costEffectiveness/components/intervention/intervention.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/components/intervention/intervention.component.scss
- src/app/pages/quickMaps/pages/costEffectiveness/components/intervention/intervention.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/components/interventionCreation/interventionCreation.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/components/interventionCreation/interventionCreation.component.ts
- Created interventionDictionaryItem.ts
- Updated api.service to return interventions from API
- updated intervention creation component to call api and pass avaliable interventions to dialog 
- updated intervention selection dialog to display selectable list of interventions
- user can select interventions, each intervention displayed accordingly
- Not currently persisting, now working on POST call
> Dw sr add intervention api

- src/app/apiAndObjects/api/api.service.ts
- src/app/apiAndObjects/api/intervention/getIntervention.ts
- src/app/apiAndObjects/objects/intervention.ts
- src/app/pages/quickMaps/pages/costEffectiveness/components/intervention/intervention.component.ts
- src/app/services/interventionData.service.ts
- Created Intervention object
- Created initial api interventions/{id} call 
- updated API service
- created InterventionData.service to contain all future intervention calls
- tested and working
> Dw sr api flesh

- .vscode/settings.json
- src/app/apiAndObjects/api/api.service.ts
- src/app/apiAndObjects/api/intervention/getInterventioData.ts
- src/app/apiAndObjects/api/intervention/getIntervention.ts
- src/app/apiAndObjects/api/intervention/getInterventionFoodVehicleStandards.ts
- src/app/apiAndObjects/api/intervention/getInterventionIndustryInformation.ts
- src/app/apiAndObjects/api/intervention/getInterventionMonitoringInformation.ts
- src/app/apiAndObjects/api/intervention/getInterventionRecurringCosts.ts
- src/app/apiAndObjects/api/intervention/getInterventionStartupCosts.ts
- src/app/apiAndObjects/api/intervention/postIntervention.ts
- src/app/apiAndObjects/objects/InterventionFoodVehicleStandards.ts
- src/app/apiAndObjects/objects/interventionData.ts
- src/app/apiAndObjects/objects/interventionIndustryInformation.ts
- src/app/apiAndObjects/objects/interventionMonitoringInformation.ts
- src/app/apiAndObjects/objects/interventionRecurringCosts.ts
- src/app/apiAndObjects/objects/interventionResponse.ts
- src/app/apiAndObjects/objects/interventionStartupCosts.ts
- src/app/pages/quickMaps/pages/costEffectiveness/components/interventionCreation/interventionCreation.component.ts
- src/app/services/interventionData.service.ts
- Flesh out all other endpoints of api
> Sr dw api flesh continued

- src/app/apiAndObjects/api/intervention/getInterventioData.ts
- src/app/apiAndObjects/objects/interventionStartupCosts.ts
- src/app/apiAndObjects/objects/misc/chartjsObject.ts
- src/app/pages/quickMaps/pages/costEffectiveness/components/intervention/intervention.component.ts
This is my impression of what we need to do for all the objects now?
> Dw 763 scale up costs

- .vscode/settings.json
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview-routing.module.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview.module.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/components/interventionReviewComponents.module.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionBaseline/interventionBaseline.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionBaseline/interventionBaseline.component.scss
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionIndustryInformation/interventionIndustryInformation.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionIndustryInformation/interventionIndustryInformation.component.scss
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionIndustryInformation/interventionIndustryInformation.component.ts
- src/app/services/interventionData.service.ts
- added industry info component, returning data from API
> feat: industryinfo component table  returning  api data

- .github/workflows/bundle.yml
- .github/workflows/deploy-staging.yml
- .github/workflows/develop-release.yml
- .github/workflows/e2e.yml
- .github/workflows/lighthouse.yml
- angular.json
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionReviewPages.scss
- update github actions
- update common js module whitelist
> update dependencies and add some allowed common js deps to list

- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/components/interventionSideNavContent/interventionSideNavContent.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionAssumptionsReview/interventionAssumptionsReview.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionAssumptionsReview/interventionAssumptionsReview.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionCompliance/interventionCompliance.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionCostSummary/interventionCostSummary.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionIndustryInformation/interventionIndustryInformation.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionIndustryInformation/interventionIndustryInformation.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionMonitoringInformation/interventionMonitoringInformation.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionMonitoringInformation/interventionMonitoringInformation.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionRecurringCosts/interventionRecurringCosts.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionStartupScaleupCosts/interventionStartupScaleupCosts.component.ts
- removed Point of consumption from sidebar stepper
- industry info table source column added, rows check for rowUnits to decide if percentage or number
- monitoring info table source column added, rows check for rowUnits to decide if percentage or number
> Intervention page tweaks

- package-lock.json
- src/app/pages/quickMaps/components/quickMapsHeader.component/quickMapsHeader.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/components/intervention/intervention.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/components/intervention/intervention.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/costEffectiveness.service.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionAssumptionsReview/interventionAssumptionsReview.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionBaseline/interventionBaseline.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionBaseline/interventionBaseline.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionCompliance/interventionCompliance.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionConsumption/interventionConsumption.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionCostSummary/interventionCostSummary.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionIndustryInformation/interventionIndustryInformation.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionMonitoringInformation/interventionMonitoringInformation.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionRecurringCosts/interventionRecurringCosts.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionStartupScaleupCosts/interventionStartupScaleupCosts.component.ts
- src/app/services/interventionData.service.ts
- Each view retrieves Id of intervention, 
-  if ID is invalid, route back to intervention creation view.
> Dw 848 service id access

- src/app/pages/quickMaps/pages/costEffectiveness/components/intervention/intervention.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionAssumptionsReview/interventionAssumptionsReview.component.ts
> chore: updated stepper so goes through correct steps

- src/app/apiAndObjects/objects/intervention.ts
- src/app/pages/quickMaps/pages/costEffectiveness/components/intervention/intervention.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/components/interventionDescription/interventionDescription.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionAssumptionsReview/interventionAssumptionsReview.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionBaseline/interventionBaseline.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionBaseline/interventionBaseline.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionCompliance/interventionCompliance.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionIndustryInformation/interventionIndustryInformation.component.ts
- src/app/services/interventionData.service.ts
- id is set in local storage
- fixed issue with data not displaying on page refresh
- id attribute added to Intervention model.
> store intervention id in local storage during review steps

- Dockerfile
- src/app/pages/quickMaps/components/sideNavContent/sideNavContent.component.html
- Fix Dockerfile so it actually builds
- Remove button for country/nation as we only support countries
- Add tooltip to disabled "Biomarker" button
> Andan v1.4 release tweaks

- src/app/components/dialogs/costEffectivenessSelectionDialog/costEffectivenessSelectionDialog.component.html
- src/app/components/dialogs/costEffectivenessSelectionDialog/costEffectivenessSelectionDialog.component.scss
- src/app/components/dialogs/costEffectivenessSelectionDialog/costEffectivenessSelectionDialog.component.ts
- src/app/components/dialogs/dialog.service.ts
- src/app/components/notifications/notification.component.html
- src/app/components/notifications/notification.component.scss
- src/app/pages/quickMaps/pages/costEffectiveness/components/intervention/intervention.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/components/intervention/intervention.component.scss
- src/assets/scss/_card.scss
- src/styles.scss
fix: leaflet map no longer shows rectangle around clicked polygon
> fix: multiple bug fixes

- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionAssumptionsReview/interventionAssumptionsReview.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionAssumptionsReview/interventionAssumptionsReview.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionCompliance/interventionCompliance.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionCompliance/interventionCompliance.component.scss
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionCompliance/interventionCompliance.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionMonitoringInformation/interventionMonitoringInformation.component.ts
- Refactored to use form
- Calling API with updated values but currently erroring :(
> Dw step 2 updates

- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionBaseline/interventionBaseline.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionBaseline/interventionBaseline.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionCompliance/interventionCompliance.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionIndustryInformation/interventionIndustryInformation.component.ts
- Refactored first table in Step 1 Baseline details to send form data to api
> Dw step 1 form submition 1

- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionIndustryInformation/interventionIndustryInformation.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionIndustryInformation/interventionIndustryInformation.component.ts
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionMonitoringInformation/interventionMonitoringInformation.component.html
- src/app/pages/quickMaps/pages/costEffectiveness/interventionReview/pages/interventionMonitoringInformation/interventionMonitoringInformation.component.ts
- When user edits GFDx button on industry or monitoring info steps the button changes to 'User Inputed'
> feat: gfdx buttons now change when row edited in monitoring and industry

- src/app/components/dialogs/apiMetadataDialog/apiMetadataDialog.component.html
- src/app/components/dialogs/apiMetadataDialog/apiMetadataDialog.component.scss
- updated version dialog to standardise with others
- from quick maps pages click the version number in footer
> style: update version dialog
